const types = {
    REQUEST_NGROK_URL: 'REQUEST_NGROK_URL',
    RECEIVE_NGROK_URL: 'RECEIVE_NGROK_URL',
    RECEIVE_USER_NAME: 'RECEIVE_USER_NAME',
    REQUEST_SIGN_UP: 'REQUEST_SIGN_UP',
    RECEIVE_SIGN_UP: 'RECEIVE_SIGN_UP',
    RECEIVE_WALLET_VERIFICATION: 'RECEIVE_WALLET_VERIFICATION',
    RECEIVE_SIGN_UP_ERROR: 'RECEIVE_SIGN_UP_ERROR',
    CREATE_USER: 'CREATE_USER',
    READ_USER: 'READ_USER',
    DELETE_USER: 'DELETE_USER',
    RECEIVE_AUTHENTICATION: 'RECEIVE_AUTHENTICATION',
    REQUEST_SIGN_OUT: 'REQUEST_SIGN_OUT',
    REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
    REQUEST_SIGN_IN_BY_NAME: 'REQUEST_SIGN_IN_BY_NAME'
};

export default types;