const types = {
    REQUEST_NGROK_URL: 'REQUEST_NGROK_URL',
    RECEIVE_NGROK_URL: 'RECEIVE_NGROK_URL',
    RECEIVE_USER_NAME: 'RECEIVE_USER_NAME',
    REQUEST_SIGN_UP: 'REQUEST_SIGN_UP',
    RECEIVE_SIGN_UP: 'RECEIVE_SIGN_UP'
};

export default types;